// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: src/coordinator/proto/txn.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Op            string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	Accounts      []string               `protobuf:"bytes,3,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Amount        int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnRequest) Reset() {
	*x = TxnRequest{}
	mi := &file_src_coordinator_proto_txn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnRequest) ProtoMessage() {}

func (x *TxnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_coordinator_proto_txn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnRequest.ProtoReflect.Descriptor instead.
func (*TxnRequest) Descriptor() ([]byte, []int) {
	return file_src_coordinator_proto_txn_proto_rawDescGZIP(), []int{0}
}

func (x *TxnRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TxnRequest) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *TxnRequest) GetAccounts() []string {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *TxnRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type TxnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnResponse) Reset() {
	*x = TxnResponse{}
	mi := &file_src_coordinator_proto_txn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnResponse) ProtoMessage() {}

func (x *TxnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_coordinator_proto_txn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnResponse.ProtoReflect.Descriptor instead.
func (*TxnResponse) Descriptor() ([]byte, []int) {
	return file_src_coordinator_proto_txn_proto_rawDescGZIP(), []int{1}
}

func (x *TxnResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_src_coordinator_proto_txn_proto protoreflect.FileDescriptor

const file_src_coordinator_proto_txn_proto_rawDesc = "" +
	"\n" +
	"\x1fsrc/coordinator/proto/txn.proto\x12\vcoordinator\"`\n" +
	"\n" +
	"TxnRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x1a\n" +
	"\baccounts\x18\x03 \x03(\tR\baccounts\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x05R\x06amount\")\n" +
	"\vTxnResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted2Q\n" +
	"\x12CoordinatorService\x12;\n" +
	"\x06Submit\x12\x17.coordinator.TxnRequest\x1a\x18.coordinator.TxnResponseBAZ?github.com/harshitster/223B-Project/src/coordinator/proto;protob\x06proto3"

var (
	file_src_coordinator_proto_txn_proto_rawDescOnce sync.Once
	file_src_coordinator_proto_txn_proto_rawDescData []byte
)

func file_src_coordinator_proto_txn_proto_rawDescGZIP() []byte {
	file_src_coordinator_proto_txn_proto_rawDescOnce.Do(func() {
		file_src_coordinator_proto_txn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_coordinator_proto_txn_proto_rawDesc), len(file_src_coordinator_proto_txn_proto_rawDesc)))
	})
	return file_src_coordinator_proto_txn_proto_rawDescData
}

var file_src_coordinator_proto_txn_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_coordinator_proto_txn_proto_goTypes = []any{
	(*TxnRequest)(nil),  // 0: coordinator.TxnRequest
	(*TxnResponse)(nil), // 1: coordinator.TxnResponse
}
var file_src_coordinator_proto_txn_proto_depIdxs = []int32{
	0, // 0: coordinator.CoordinatorService.Submit:input_type -> coordinator.TxnRequest
	1, // 1: coordinator.CoordinatorService.Submit:output_type -> coordinator.TxnResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_coordinator_proto_txn_proto_init() }
func file_src_coordinator_proto_txn_proto_init() {
	if File_src_coordinator_proto_txn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_coordinator_proto_txn_proto_rawDesc), len(file_src_coordinator_proto_txn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_coordinator_proto_txn_proto_goTypes,
		DependencyIndexes: file_src_coordinator_proto_txn_proto_depIdxs,
		MessageInfos:      file_src_coordinator_proto_txn_proto_msgTypes,
	}.Build()
	File_src_coordinator_proto_txn_proto = out.File
	file_src_coordinator_proto_txn_proto_goTypes = nil
	file_src_coordinator_proto_txn_proto_depIdxs = nil
}
