// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: code/proto/client.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxnStatusUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxnId  string `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "COMMITTED", "ABORTED", "DISCARDED"
}

func (x *TxnStatusUpdate) Reset() {
	*x = TxnStatusUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code_proto_client_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnStatusUpdate) ProtoMessage() {}

func (x *TxnStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_code_proto_client_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnStatusUpdate.ProtoReflect.Descriptor instead.
func (*TxnStatusUpdate) Descriptor() ([]byte, []int) {
	return file_code_proto_client_proto_rawDescGZIP(), []int{0}
}

func (x *TxnStatusUpdate) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *TxnStatusUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ClientAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ClientAck) Reset() {
	*x = ClientAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code_proto_client_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAck) ProtoMessage() {}

func (x *ClientAck) ProtoReflect() protoreflect.Message {
	mi := &file_code_proto_client_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAck.ProtoReflect.Descriptor instead.
func (*ClientAck) Descriptor() ([]byte, []int) {
	return file_code_proto_client_proto_rawDescGZIP(), []int{1}
}

func (x *ClientAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_code_proto_client_proto protoreflect.FileDescriptor

var file_code_proto_client_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x6f, 0x64, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22,
	0x40, 0x0a, 0x0f, 0x54, 0x78, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x78, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x78, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x25, 0x0a, 0x09, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x4b, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x10, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x54, 0x78, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x15, 0x2e,
	0x63, 0x6f, 0x64, 0x65, 0x2e, 0x54, 0x78, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x1a, 0x0f, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x41, 0x63, 0x6b, 0x42, 0x12, 0x5a, 0x10, 0x63, 0x6f, 0x64, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_code_proto_client_proto_rawDescOnce sync.Once
	file_code_proto_client_proto_rawDescData = file_code_proto_client_proto_rawDesc
)

func file_code_proto_client_proto_rawDescGZIP() []byte {
	file_code_proto_client_proto_rawDescOnce.Do(func() {
		file_code_proto_client_proto_rawDescData = protoimpl.X.CompressGZIP(file_code_proto_client_proto_rawDescData)
	})
	return file_code_proto_client_proto_rawDescData
}

var file_code_proto_client_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_code_proto_client_proto_goTypes = []interface{}{
	(*TxnStatusUpdate)(nil), // 0: code.TxnStatusUpdate
	(*ClientAck)(nil),       // 1: code.ClientAck
}
var file_code_proto_client_proto_depIdxs = []int32{
	0, // 0: code.ClientService.ReceiveTxnStatus:input_type -> code.TxnStatusUpdate
	1, // 1: code.ClientService.ReceiveTxnStatus:output_type -> code.ClientAck
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_code_proto_client_proto_init() }
func file_code_proto_client_proto_init() {
	if File_code_proto_client_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_code_proto_client_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxnStatusUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_code_proto_client_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_code_proto_client_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_code_proto_client_proto_goTypes,
		DependencyIndexes: file_code_proto_client_proto_depIdxs,
		MessageInfos:      file_code_proto_client_proto_msgTypes,
	}.Build()
	File_code_proto_client_proto = out.File
	file_code_proto_client_proto_rawDesc = nil
	file_code_proto_client_proto_goTypes = nil
	file_code_proto_client_proto_depIdxs = nil
}
