// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: code/proto/client.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxnStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "COMMITTED", "ABORTED", "DISCARDED"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnStatusUpdate) Reset() {
	*x = TxnStatusUpdate{}
	mi := &file_code_proto_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnStatusUpdate) ProtoMessage() {}

func (x *TxnStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_code_proto_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnStatusUpdate.ProtoReflect.Descriptor instead.
func (*TxnStatusUpdate) Descriptor() ([]byte, []int) {
	return file_code_proto_client_proto_rawDescGZIP(), []int{0}
}

func (x *TxnStatusUpdate) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *TxnStatusUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ClientAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientAck) Reset() {
	*x = ClientAck{}
	mi := &file_code_proto_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAck) ProtoMessage() {}

func (x *ClientAck) ProtoReflect() protoreflect.Message {
	mi := &file_code_proto_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAck.ProtoReflect.Descriptor instead.
func (*ClientAck) Descriptor() ([]byte, []int) {
	return file_code_proto_client_proto_rawDescGZIP(), []int{1}
}

func (x *ClientAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_code_proto_client_proto protoreflect.FileDescriptor

const file_code_proto_client_proto_rawDesc = "" +
	"\n" +
	"\x17code/proto/client.proto\x12\x04code\"@\n" +
	"\x0fTxnStatusUpdate\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"%\n" +
	"\tClientAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2K\n" +
	"\rClientService\x12:\n" +
	"\x10ReceiveTxnStatus\x12\x15.code.TxnStatusUpdate\x1a\x0f.code.ClientAckB\x12Z\x10code/proto;protob\x06proto3"

var (
	file_code_proto_client_proto_rawDescOnce sync.Once
	file_code_proto_client_proto_rawDescData []byte
)

func file_code_proto_client_proto_rawDescGZIP() []byte {
	file_code_proto_client_proto_rawDescOnce.Do(func() {
		file_code_proto_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_code_proto_client_proto_rawDesc), len(file_code_proto_client_proto_rawDesc)))
	})
	return file_code_proto_client_proto_rawDescData
}

var file_code_proto_client_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_code_proto_client_proto_goTypes = []any{
	(*TxnStatusUpdate)(nil), // 0: code.TxnStatusUpdate
	(*ClientAck)(nil),       // 1: code.ClientAck
}
var file_code_proto_client_proto_depIdxs = []int32{
	0, // 0: code.ClientService.ReceiveTxnStatus:input_type -> code.TxnStatusUpdate
	1, // 1: code.ClientService.ReceiveTxnStatus:output_type -> code.ClientAck
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_code_proto_client_proto_init() }
func file_code_proto_client_proto_init() {
	if File_code_proto_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_code_proto_client_proto_rawDesc), len(file_code_proto_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_code_proto_client_proto_goTypes,
		DependencyIndexes: file_code_proto_client_proto_depIdxs,
		MessageInfos:      file_code_proto_client_proto_msgTypes,
	}.Build()
	File_code_proto_client_proto = out.File
	file_code_proto_client_proto_goTypes = nil
	file_code_proto_client_proto_depIdxs = nil
}
