// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: code/proto/txn.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Op            string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	Accounts      []string               `protobuf:"bytes,3,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Amount        int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	ClientAddr    string                 `protobuf:"bytes,5,opt,name=client_addr,json=clientAddr,proto3" json:"client_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnRequest) Reset() {
	*x = TxnRequest{}
	mi := &file_code_proto_txn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnRequest) ProtoMessage() {}

func (x *TxnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_code_proto_txn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnRequest.ProtoReflect.Descriptor instead.
func (*TxnRequest) Descriptor() ([]byte, []int) {
	return file_code_proto_txn_proto_rawDescGZIP(), []int{0}
}

func (x *TxnRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TxnRequest) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *TxnRequest) GetAccounts() []string {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *TxnRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TxnRequest) GetClientAddr() string {
	if x != nil {
		return x.ClientAddr
	}
	return ""
}

type TxnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnResponse) Reset() {
	*x = TxnResponse{}
	mi := &file_code_proto_txn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnResponse) ProtoMessage() {}

func (x *TxnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_code_proto_txn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnResponse.ProtoReflect.Descriptor instead.
func (*TxnResponse) Descriptor() ([]byte, []int) {
	return file_code_proto_txn_proto_rawDescGZIP(), []int{1}
}

func (x *TxnResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_code_proto_txn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_code_proto_txn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_code_proto_txn_proto_rawDescGZIP(), []int{2}
}

func (x *GetStatusRequest) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

type GetStatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // One of: "PENDING", "PREPARED", "COMMITTED", "ABORTED", "UNKNOWN"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusReply) Reset() {
	*x = GetStatusReply{}
	mi := &file_code_proto_txn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusReply) ProtoMessage() {}

func (x *GetStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_code_proto_txn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusReply.ProtoReflect.Descriptor instead.
func (*GetStatusReply) Descriptor() ([]byte, []int) {
	return file_code_proto_txn_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AckTxnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckTxnRequest) Reset() {
	*x = AckTxnRequest{}
	mi := &file_code_proto_txn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckTxnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckTxnRequest) ProtoMessage() {}

func (x *AckTxnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_code_proto_txn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckTxnRequest.ProtoReflect.Descriptor instead.
func (*AckTxnRequest) Descriptor() ([]byte, []int) {
	return file_code_proto_txn_proto_rawDescGZIP(), []int{4}
}

func (x *AckTxnRequest) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

type CoordAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordAck) Reset() {
	*x = CoordAck{}
	mi := &file_code_proto_txn_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordAck) ProtoMessage() {}

func (x *CoordAck) ProtoReflect() protoreflect.Message {
	mi := &file_code_proto_txn_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordAck.ProtoReflect.Descriptor instead.
func (*CoordAck) Descriptor() ([]byte, []int) {
	return file_code_proto_txn_proto_rawDescGZIP(), []int{5}
}

func (x *CoordAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_code_proto_txn_proto protoreflect.FileDescriptor

const file_code_proto_txn_proto_rawDesc = "" +
	"\n" +
	"\x14code/proto/txn.proto\x12\x04code\"\x81\x01\n" +
	"\n" +
	"TxnRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x1a\n" +
	"\baccounts\x18\x03 \x03(\tR\baccounts\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x05R\x06amount\x12\x1f\n" +
	"\vclient_addr\x18\x05 \x01(\tR\n" +
	"clientAddr\")\n" +
	"\vTxnResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\")\n" +
	"\x10GetStatusRequest\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\"(\n" +
	"\x0eGetStatusReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"&\n" +
	"\rAckTxnRequest\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\"$\n" +
	"\bCoordAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xaa\x01\n" +
	"\x12CoordinatorService\x12*\n" +
	"\x03Txn\x12\x10.code.TxnRequest\x1a\x11.code.TxnResponse\x129\n" +
	"\tGetStatus\x12\x16.code.GetStatusRequest\x1a\x14.code.GetStatusReply\x12-\n" +
	"\x06AckTxn\x12\x13.code.AckTxnRequest\x1a\x0e.code.CoordAckB\x12Z\x10code/proto;protob\x06proto3"

var (
	file_code_proto_txn_proto_rawDescOnce sync.Once
	file_code_proto_txn_proto_rawDescData []byte
)

func file_code_proto_txn_proto_rawDescGZIP() []byte {
	file_code_proto_txn_proto_rawDescOnce.Do(func() {
		file_code_proto_txn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_code_proto_txn_proto_rawDesc), len(file_code_proto_txn_proto_rawDesc)))
	})
	return file_code_proto_txn_proto_rawDescData
}

var file_code_proto_txn_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_code_proto_txn_proto_goTypes = []any{
	(*TxnRequest)(nil),       // 0: code.TxnRequest
	(*TxnResponse)(nil),      // 1: code.TxnResponse
	(*GetStatusRequest)(nil), // 2: code.GetStatusRequest
	(*GetStatusReply)(nil),   // 3: code.GetStatusReply
	(*AckTxnRequest)(nil),    // 4: code.AckTxnRequest
	(*CoordAck)(nil),         // 5: code.CoordAck
}
var file_code_proto_txn_proto_depIdxs = []int32{
	0, // 0: code.CoordinatorService.Txn:input_type -> code.TxnRequest
	2, // 1: code.CoordinatorService.GetStatus:input_type -> code.GetStatusRequest
	4, // 2: code.CoordinatorService.AckTxn:input_type -> code.AckTxnRequest
	1, // 3: code.CoordinatorService.Txn:output_type -> code.TxnResponse
	3, // 4: code.CoordinatorService.GetStatus:output_type -> code.GetStatusReply
	5, // 5: code.CoordinatorService.AckTxn:output_type -> code.CoordAck
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_code_proto_txn_proto_init() }
func file_code_proto_txn_proto_init() {
	if File_code_proto_txn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_code_proto_txn_proto_rawDesc), len(file_code_proto_txn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_code_proto_txn_proto_goTypes,
		DependencyIndexes: file_code_proto_txn_proto_depIdxs,
		MessageInfos:      file_code_proto_txn_proto_msgTypes,
	}.Build()
	File_code_proto_txn_proto = out.File
	file_code_proto_txn_proto_goTypes = nil
	file_code_proto_txn_proto_depIdxs = nil
}
